import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavDock } from "@/components/navbar/dock";
import WalletContextProvider from "@/lib/walletContextProvider";
import { WalletProvider as CustomWalletProvider } from "@/lib/walletContext";
import { ReduxProviders } from "@/lib/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProviders>

            <WalletContextProvider>
              <CustomWalletProvider>
                <NavDock />
                <main >
                  {children}
                </main>
              </CustomWalletProvider>
            </WalletContextProvider>
          </ReduxProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
